scopes:
    status:
        label: vojtasvoboda.reservations::lang.reservation.status
        modelClass: VojtaSvoboda\Reservations\Models\Status
        nameFrom: name
        conditions: status_id in (:filtered)
